# author:  Valeria Molina Recinos

trigger:
  branches:
    include:
      - release
    exclude: # Trigger excludes changes made to the pipeline.
      - "devops"


parameters: # Parameters show up in the azure devops gui. These can be modified for manual runs but will use the default values when triggered by changes to the repo.

  - name: TriggerRelease # If true, tag the build for release. This will cause a successful completion of the build pipeline to trigger the release pipeline.
    type: boolean
    default: true
    values:
      - true
      - false
  - name: UseAzureKeyVault # If true, the pipeline will import secrets from the azure keyvault specified in the variables.
    type: boolean
    default: true
    values:
      - true
      - false
  - name: ListDirectories # If true, the pipeline will list directories in the prebuild. This is used for identifying paths in the build environment.
    type: boolean
    default: true
    values:
      - true
      - false
  - name: RunSonarQube # If true, the pipeline will run sonarqube scanning for code quality checks.
    type: boolean
    default: false
    values:
      - true
      - false
  - name: HCLAppScan # If true, the pipeline will run HCL Appscan for code security checks.
    type: boolean
    default: false
    values:
      - true
      - false
  - name: BuildImg # If true, the pipeline will build the docker image.
    type: boolean
    default: true
    values:
      - true
      - false
  - name: PushImg # If true, the pipeline will push the docker image to the specified ACR.
    type: boolean
    default: true
    values:
      - true
      - false

resources:
  repositories:
    - repository: rbs-devops-shared-hclappscan-testing
      type: github
      endpoint: 'rbs-nextgenpos'
      name: RoyalAholdDelhaize/rbs-devops-shared-hclappscan-testing
      ref: refs/tags/1.0.1
    - repository: rbs-devops-shared-sonarqube-testing
      type: github
      endpoint: 'rbs-nextgenpos'
      name: RoyalAholdDelhaize/rbs-devops-shared-sonarqube-testing
      ref: refs/tags/1.0.5

variables:
- template: ..\data\variables.yml

pool: 'nextgenpos-ubuntu-2004-agentpool'

stages:
# The setup stage prepares the pipeline for future tasks. Keyvault vars are imported, pipeline vars are updated, and directories are listed as the parameters allow.
  - stage: PreBuild
    displayName: SetUp
    jobs:
      - job: PreBuild
        displayName: PreBuild
        steps:
          - task: PowerShell@2
            condition: and(succeeded(), ${{parameters.ListDirectories}})
            displayName: List Directories
            inputs:
              targetType: 'inline'
              script: |
                Get-ChildItem -Recurse .

# Dev stage builds code, runs tests, and publishes artifiacts environment parameters set to dev.
  - stage: DevStage
    dependsOn: PreBuild
    displayName: Dev Build
    jobs:
      - template: /devops/pipelines/jobs.build-test-publish.yml
        parameters:
          environment: dev
          UseAzureKeyVault: ${{parameters.UseAzureKeyVault}}
          RunSonarQube: ${{parameters.RunSonarQube}}
          HCLAppScan: ${{parameters.HCLAppScan}}
          BuildImg: ${{parameters.BuildImg}}
          PushImg: ${{parameters.PushImg}}
